"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Tintuyendung", [
      {
        tieude: "Software Engineer",
        mota: "Join our dynamic team to develop innovative software solutions.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 1, // Corresponding Nhatuyendung ID
        trangthai: "Open",
        diachi: "123 Tech Way",
        mucluong: "$70,000 - $90,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Frontend Developer",
        mota: "We are looking for a skilled frontend developer to work on our client applications.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 2,
        trangthai: "Open",
        diachi: "456 Code Street",
        mucluong: "$60,000 - $80,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Backend Developer",
        mota: "Join our backend team and work with modern tech stacks.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 3,
        trangthai: "Open",
        diachi: "789 Dev Road",
        mucluong: "$75,000 - $95,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Data Scientist",
        mota: "Analyze large datasets to drive company insights.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 4,
        trangthai: "Open",
        diachi: "234 Data Ave",
        mucluong: "$85,000 - $105,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Full Stack Developer",
        mota: "Opportunity for a full stack developer to join our innovative team.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 5,
        trangthai: "Open",
        diachi: "567 Stack Blvd",
        mucluong: "$80,000 - $100,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "DevOps Engineer",
        mota: "Seeking an experienced DevOps engineer.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 6,
        trangthai: "Open",
        diachi: "890 Cloud Path",
        mucluong: "$90,000 - $110,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Project Manager",
        mota: "Manage multiple IT projects with a team of talented individuals.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 7,
        trangthai: "Open",
        diachi: "321 PM Rd",
        mucluong: "$100,000 - $120,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "UX/UI Designer",
        mota: "Craft exceptional user experiences as a UX/UI designer.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 3)),
        nhatuyendung_id: 8,
        trangthai: "Open",
        diachi: "654 Design St",
        mucluong: "$65,000 - $85,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Product Owner",
        mota: "Lead product development from ideation to execution.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 9,
        trangthai: "Open",
        diachi: "987 Product Rd",
        mucluong: "$95,000 - $115,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Tech Support",
        mota: "Provide technical support to our clients.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 10,
        trangthai: "Open",
        diachi: "101 Support Ln",
        mucluong: "$50,000 - $70,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Business Analyst",
        mota: "Analyze business needs and translate them into technical requirements.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 11,
        trangthai: "Open",
        diachi: "202 Business St",
        mucluong: "$70,000 - $90,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Mobile Developer",
        mota: "Develop cutting-edge mobile applications with our team.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 3)),
        nhatuyendung_id: 12,
        trangthai: "Open",
        diachi: "303 Mobile Ln",
        mucluong: "$85,000 - $105,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Network Security Engineer",
        mota: "Ensure the security of our organization's networks.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 13,
        trangthai: "Open",
        diachi: "404 Secure Blvd",
        mucluong: "$95,000 - $115,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "System Administrator",
        mota: "Maintain and support our internal IT systems.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 14,
        trangthai: "Open",
        diachi: "505 SysAdmin Ave",
        mucluong: "$75,000 - $95,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Database Administrator",
        mota: "Manage and safeguard our data assets.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 3)),
        nhatuyendung_id: 15,
        trangthai: "Open",
        diachi: "606 Data Rd",
        mucluong: "$85,000 - $105,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "IT Technician",
        mota: "Provide technical support and maintenance of workstations and networks.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 16,
        trangthai: "Open",
        diachi: "707 Tech Ln",
        mucluong: "$55,000 - $75,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Quality Assurance Tester",
        mota: "Ensure the quality and reliability of our applications.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 17,
        trangthai: "Open",
        diachi: "808 QA Cir",
        mucluong: "$65,000 - $85,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Cybersecurity Specialist",
        mota: "Protect our digital infrastructure from threats.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 3)),
        nhatuyendung_id: 18,
        trangthai: "Open",
        diachi: "909 Cyber St",
        mucluong: "$90,000 - $110,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "AI/ML Engineer",
        mota: "Develop and implement machine learning models.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 1)),
        nhatuyendung_id: 19,
        trangthai: "Open",
        diachi: "505 AI Ave",
        mucluong: "$120,000 - $140,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        tieude: "Cloud Solutions Architect",
        mota: "Design cloud-based solutions tailored to our clients' needs.",
        Ngayhethan: new Date(new Date().setMonth(new Date().getMonth() + 2)),
        nhatuyendung_id: 20,
        trangthai: "Open",
        diachi: "606 Cloud Blvd",
        mucluong: "$105,000 - $125,000",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("Tintuyendung", null, {});
  },
};
